name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  # The number of days to retain artifacts
  RETENTION_DAYS: 30

jobs:

  build-linux:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsfml-dev

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: actions/upload-artifact@v4
      with:
        name: fmcomposer-linux
        path: |
          ${{github.workspace}}/build/bin/FMComposer
          ${{github.workspace}}/build/bin/defaultkeyboards.ini
          ${{github.workspace}}/build/bin/gmlist.ini
          ${{github.workspace}}/build/bin/readme.txt
          ${{github.workspace}}/build/bin/instruments
          ${{github.workspace}}/build/bin/songs
          ${{github.workspace}}/build/bin/themes
        retention-days: ${{env.RETENTION_DAYS}}

  build-win64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake MSVC
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build MSVC
        run: cmake --build build --config ${{env.BUILD_TYPE}}
      - uses: actions/upload-artifact@v4
        with:
          name: fmcomposer-win64
          path: |
            build/bin/FMComposer.exe
            build/bin/*.dll
            build/bin/defaultkeyboards.ini
            build/bin/gmlist.ini
            build/bin/readme.txt
            build/bin/instruments
            build/bin/songs
            build/bin/themes
          retention-days: ${{env.RETENTION_DAYS}}